[package]
name = "Smoothy-Client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.28.4"
time = {version = "0.3.20", features = ["local-offset"]}
